### PR TITLE
Pretty dates

### PR DESCRIPTION
**Pull request by johnklehm**
Stop hurting myself as I try to read the epochs from prism-prod dynamodb.

### CODE REVIEW

**Comment by johnklehm** [comment]
docker build --no-cache . -t dynamodb-viewer && docker run -e "DYNAMO_ENDPOINT=dynamodb.us-east-1.amazonaws.com" -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -p 8002:8001 --name dynamodb-viewer dynamodb-viewer

**Comment by alexsk7** [comment]
Seems like there might be an issue @johnklehm. It's probably something I'm doing though.

```IncompleteSignatureException: 'region/dynamodb/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=A#######################/default region/dynamodb/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=##############################################'.
    at Request.extractError (/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)```

**Comment by johnklehm** [comment]
Slanderous!  It was working for me Friday, checking now...

> Seems like there might be an issue @johnklehm. It's probably something I'm doing though.
> 
> ```
>     at Request.extractError (/node_modules/aws-sdk/lib/protocol/json.js:51:27)
>     at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>     at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>     at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
>     at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
>     at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:685:12)
>     at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)```
> ```

**Comment by johnklehm** [comment]
Talked this one out, new env var for this tool env AWS_REGION needs to be set...needs to match the dynamodb endpoint region.

**Review by alexsk7 — APPROVED** [review]

**Pull request merged**
